# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    metallb-config.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mvan-eyn <mvan-eyn@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/10/29 10:04:24 by mvan-eyn          #+#    #+#              #
#    Updated: 2020/11/08 13:30:13 by mvan-eyn         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
      - name: default
        protocol: layer2
        addresses:
          - 192.168.99.230-192.168.99.240