# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    deployment.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mvan-eyn <mvan-eyn@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/10/31 12:54:08 by mvan-eyn          #+#    #+#              #
#    Updated: 2020/11/06 18:35:02 by mvan-eyn         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-maria
  namespace: default
  labels:
    app: dep-maria
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: img-mariadb
        imagePullPolicy: Never
        volumeMounts:
          - name: pv-maria
            mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
      volumes:
        - name: pv-maria
          persistentVolumeClaim:
            claimName: pvc-maria
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mariadb
spec:
  selector:
    app: mariadb
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306

