# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    deployment.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mvan-eyn <mvan-eyn@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/02 16:17:31 by mvan-eyn          #+#    #+#              #
#    Updated: 2020/11/02 16:33:19 by mvan-eyn         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: img-telegraf
        imagePullPolicy: Never
        ports:
        - containerPort: 8125
        volumeMounts:
        - name: telegraf-endpoint
          mountPath: "/var/run/docker.sock"
      volumes:
      - name: telegraf-endpoint
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: svc-telegraf
spec:
  selector:
    app: telegraf
  type: ClusterIP
  ports:
  - port: 8125
    targetPort: 8125
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-telegraf
  labels:
    app: telegraf

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-telegraf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: account-telegraf
  namespace: default
